# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-10-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.CharField(max_length=1000)),
                ('tipo', models.CharField(choices=[('rotina', 'Rotina'), ('pronto_atendimento', 'Pronto_Atendimento'), ('acompanhamento', 'Acompanhamento')], max_length=20)),
                ('especialidade', models.CharField(max_length=50)),
                ('medico', models.CharField(max_length=500)),
                ('telefone', models.IntegerField()),
                ('dataconsulta', models.DateField(verbose_name='Data_da_Consulta')),
                ('dataretorno', models.DateField(verbose_name='Data_do_Retorno')),
                ('arquivo1', models.FileField(upload_to='images')),
                ('arquivo2', models.FileField(upload_to='images')),
                ('arquivo3', models.FileField(upload_to='images')),
                ('arquivo4', models.FileField(upload_to='images')),
                ('arquivo5', models.FileField(upload_to='images')),
                ('arquivo6', models.FileField(upload_to='images')),
                ('arquivo7', models.FileField(upload_to='images')),
                ('evolucao_tratamento', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(max_length=50)),
                ('naturalidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='consultas',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente'),
        ),
    ]
