# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-10-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.CharField(max_length=1000)),
                ('tipo', models.CharField(choices=[('rotina', 'Rotina'), ('pronto_atendimento', 'Pronto Atendimento'), ('acompanhamento', 'Acompanhamento')], max_length=20)),
                ('especialidade', models.CharField(max_length=50)),
                ('medico', models.CharField(max_length=500)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('dataconsulta', models.DateField(verbose_name='Data da Consulta')),
                ('dataretorno', models.DateField(blank=True, null=True, verbose_name='Data do Retorno')),
                ('arquivo1', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo2', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo3', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo4', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo5', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo6', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo7', models.FileField(blank=True, null=True, upload_to='images')),
                ('evolucao_tratamento', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Evolução do Tratamento')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Mãe')),
                ('naturalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente'),
        ),
    ]
