# Generated by Django 3.2.8 on 2021-10-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Mãe')),
                ('naturalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('rotina', 'Rotina'), ('pronto_atendimento', 'Pronto Atendimento'), ('acompanhamento', 'Acompanhamento'), ('medicamento uso contínuo', 'Medicamento uso Contínuo'), ('vacinação', 'Vacinação')], max_length=24)),
                ('dataconsulta', models.DateField(verbose_name='Data da Consulta')),
                ('especialidade', models.CharField(blank=True, max_length=50, null=True)),
                ('medico', models.CharField(blank=True, max_length=500, null=True)),
                ('crm', models.CharField(blank=True, max_length=500, null=True, verbose_name='CRM')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('sintomas', models.CharField(max_length=1000, verbose_name='Sintomas / Motivo')),
                ('diagnostico', models.CharField(blank=True, max_length=1000, null=True)),
                ('medicamento', models.CharField(blank=True, max_length=1000, null=True)),
                ('evolucao_tratamento', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Evolução do Tratamento')),
                ('dataretorno', models.DateField(blank=True, null=True, verbose_name='Data do Retorno')),
                ('arquivo1', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo2', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo3', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo4', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo5', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo6', models.FileField(blank=True, null=True, upload_to='images')),
                ('arquivo7', models.FileField(blank=True, null=True, upload_to='images')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
    ]
